# roles/mysql/vars/main.yml

mysql_root_password: ""
mysql_databases:
  - name: tooling
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: webaccess
    host: "172.31.33.37"
    password: Admin123#
    priv: "tooling.*:ALL"
