# roles/mysql/vars/main.yml

mysql_root_password: ""
mysql_databases:
  - name: tooling
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: admin
    host: "172.31.2.161"
    password: admin
    priv: "tooling.*:ALL"
