---
- hosts: all
  name: Include dynamic variables
  become: yes
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

# - import_playbook: ../static-assignments/common.yml

- name: tooling assignment
  import_playbook: ../static-assignments/uat-webservers.yml
  tags:
    - webservers

- name: Nginx assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  tags:
    - nginx_lb

- name: Database assignment
  import_playbook: ../static-assignments/db-servers.yml
  tags:
    - db
